### ISSUE TITLE
login example not working

### ISSUE THREAD

**Issue by j2l** [gamestdio/colyseus-examples#10]
I run colyseus examples on glitch (free NodeJS hosting), it works fine.
But the auth example is puzzling me, I get:
![image](https://user-images.githubusercontent.com/65325/49441718-a4309500-f7c7-11e8-9c1c-e49fe69c997c.png)
Additionally, I see a token in clear in the code. I guess it should be in .env file
I also tried in FF (where my facebook cookie is) and it throws another error:
![image](https://user-images.githubusercontent.com/65325/49441877-1a34fc00-f7c8-11e8-9f36-30515f5cdfb8.png)

**Comment by endel** [comment]
Hi @j2l, you need to create your own [Facebook App](https://developers.facebook.com/), register your domain on their dashboard, and use your own app token here: https://github.com/gamestdio/colyseus-examples/blob/master/rooms/03-auth.ts#L4

Hope this helps
