### ISSUE TITLE
Cloned, npm install, then npm start and get an error

### ISSUE THREAD

**Issue by admazzola** [gamestdio/colyseus-examples#4]
Using Node 6 I followed your instructions exactly and get this error:

Error: Cannot find module '/home/andy/dev/colyseus-examples/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

It seems like the index.ts file is never being compiled to index.js -- is that the issue?  I dont see any use of webpack or anything so how would this even be done anyways ?

**Comment by endel** [comment]
Hey @admazzola, thanks for reporting. I've just updated the npm task to use `ts-node` instead of `node` for development purposes. On production, it's not recommended to use `ts-node` though.

Cheers!

**Comment by endel** [comment]
This repository demonstrates mostly how the backend should look like.

For the frontend, you may use different libraries such as PIXI / THREE.js / Babylon, etc, and each one of them can have its own particularities when it comes to the webpack config. I'm not sure this should live on this repository.
