### ISSUE TITLE
`npm start` on Windows10 throws error, fixed by minor change to package.json

### ISSUE THREAD

**Issue by derricw** [gamestdio/colyseus-examples#6]
Here is the error:

> colyseus-examples@1.0.0 start C:\Users\derricw\Documents\github\colyseus-examples
> nodemon --watch '**/*.ts' --exec 'ts-node' index.ts

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: '**/*.ts'
[nodemon] starting `'ts-node' index.ts`
''ts-node'' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...

And I fixed it by deleting the single quotes around 'ts-node' in `line 7` in package.json from:

   ` "start": "nodemon --watch '**/*.ts' --exec 'ts-node' index.ts",`
to:
   ` "start": "nodemon --watch '**/*.ts' --exec ts-node index.ts",`

**Comment by endel** [comment]
Thanks a lot @derricw! I've just applied this change as you suggested. Cheers!
