### ISSUE TITLE
Facebook API refuses OAuth when called from HTTP

### ISSUE THREAD

**Issue by RandyStevens** [gamestdio/colyseus-examples#9]
### Description

chrome console gives this error
```
The method FB.login will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/
```

**Comment by NOOMA-42** [comment]
Hi I wonder why this issue was closed. It seems not solved yet? :D

**Comment by endel** [comment]
Hi @NOOMA-42, since October 2018, Facebook is requiring any app to use `https`: https://developers.facebook.com/docs/facebook-login/security#https

Using plain `http` is not an option. Cheers.
